// Minimal structural shapes the code generators depend on. The concrete
// Element/Descriptor classes satisfy these, and tests can pass plain objects.
export interface CodeElement {
    name: string
    comment: string
    value: unknown
    toByteArray(): Uint8Array
}

export interface CodeDescriptor {
    name: string
    index: number
    elements: CodeElement[]
    children: CodeDescriptor[]
}

// Per-language rendering rules. The shared generator below walks the descriptor
// tree; each LangSpec supplies only the syntactic differences.
interface LangSpec {
    banner: string
    arrayOpen(name: string, byteLength: number): string
    arrayClose: string
    indent: string
    descriptorComment(name: string): string
    fieldComment(text: string): string
    identifier(name: string, index: number): string
    // Column the trailing field comment is aligned to.
    commentColumn: number
}

// A string-valued element (e.g. bString) shows the decoded string in its comment.
function fieldCommentText(element: CodeElement): string {
    const base = `${element.name}: ${element.comment}`
    return typeof element.value === 'string' ? `${base} "${element.value}"` : base
}

function dumpElement(element: CodeElement, spec: LangSpec): string {
    const tokens = Array.from(element.toByteArray()).map(
        (b) => '0x' + b.toString(16).padStart(2, '0') + ','
    )

    // Four bytes per row. The comment attaches to the last row that has bytes,
    // never to a trailing empty line.
    const rows: string[] = []
    for (let i = 0; i < tokens.length; i += 4) {
        rows.push(spec.indent + tokens.slice(i, i + 4).join(' '))
    }
    if (rows.length === 0) {
        rows.push(spec.indent)
    }

    const last = rows.length - 1
    const padding = Math.max(1, spec.commentColumn - rows[last].length)
    rows[last] += ' '.repeat(padding) + spec.fieldComment(fieldCommentText(element))

    return rows.join('\n') + '\n'
}

function totalBytes(descriptor: CodeDescriptor): number {
    const own = descriptor.elements.reduce((total, e) => total + e.toByteArray().length, 0)
    return descriptor.children.reduce((total, child) => total + totalBytes(child), own)
}

function dumpDescriptor(descriptor: CodeDescriptor, spec: LangSpec): string {
    let s = spec.descriptorComment(descriptor.name) + '\n'

    for (const element of descriptor.elements) {
        s += dumpElement(element, spec)
    }

    for (const child of descriptor.children) {
        s += dumpDescriptor(child, spec)
    }

    return s
}

function generate(descriptors: CodeDescriptor[], spec: LangSpec): string {
    let s = spec.banner

    for (const descriptor of descriptors) {
        s += spec.arrayOpen(spec.identifier(descriptor.name, descriptor.index), totalBytes(descriptor))
        s += '\n'
        s += dumpDescriptor(descriptor, spec)
        s += spec.arrayClose + '\n\n'
    }

    return s
}

const cSpec: LangSpec = {
    banner: `\n/*\n * Auto-generated by USB Descryptor\n */\n\n`,
    arrayOpen: (name) => `static const unsigned char ${name}[] = {`,
    arrayClose: '};',
    indent: '  ',
    descriptorComment: (name) => `  /* ${name} */`,
    fieldComment: (text) => `/* ${text} */`,
    identifier: (name, index) => `${name.replace(/ /g, '')}_${index}`,
    commentColumn: 32
}

const rustSpec: LangSpec = {
    banner: `// Auto-generated by USB Descryptor\n\n`,
    arrayOpen: (name, byteLength) => `static ${name}: [u8; ${byteLength}] = [`,
    arrayClose: '];',
    indent: '    ',
    descriptorComment: (name) => `    // ${name}`,
    fieldComment: (text) => `// ${text}`,
    identifier: (name, index) => `${name.trim().split(/\s+/).join('_').toUpperCase()}_${index}`,
    commentColumn: 35
}

export function generateC(descriptors: CodeDescriptor[]): string {
    return generate(descriptors, cSpec)
}

export function generateRust(descriptors: CodeDescriptor[]): string {
    return generate(descriptors, rustSpec)
}
