<script setup lang="ts">
import { ref } from 'vue';
import { NSelect, NFlex, NButton, useMessage } from 'naive-ui';
import { useDescriptorStore } from '@/stores/descriptor';
import { Copy16Regular } from '@vicons/fluent';
import { Icon } from '@vicons/utils';
import { Descriptor } from '../usb/descriptors';

import hljs from 'highlight.js';

const store = useDescriptorStore();
const message = useMessage();

const languages = [
    {
        label: 'C',
        value: 'c'
    }
];

const language = ref(languages[0].value);

function codeC(): string {
    let s = `
/*
 * Auto-generated by USBDescrptor
 */

`;

    function hexDump(buffer: Uint8Array): string {
        return Array.from(buffer)
            .map((b, i) => '0x' + b.toString(16).padStart(2, '0') + ((i + 1) % 4 === 0 ? ',\n ' : ','))
            .join(' ');
    }

    function dumpDescriptor(descriptor: Descriptor): string {
        let s = `  /* ${descriptor.name} */\n`;

        for (const element of descriptor.elements) {
            const b = hexDump(element.toByteArray());
            s += '  ' + b;

            const lines = b.split('\n');

            let l = lines[lines.length - 1].length;

            if (lines.length > 1)
                l -= 2;

            if (l < 32)
                s += ' '.repeat(32 - l);

            s += ` /* ${element.name}: ${element.comment} */\n`;
        }

        for (const child of descriptor.children)
            s += dumpDescriptor(child);

        return s;
    }

    for (const descriptor of store.descriptors) {
        s += `static const unsigned char ${descriptor.name.replace(/ */g, '')}_${descriptor.index}[] = {\n`
        s += dumpDescriptor(descriptor);
        s += '};\n';
        s += '\n';
    }

    return s;
}

function code(): string {
    let s = '';

    switch (language.value) {
        case 'c':
            s = codeC();
    }

    return s;
}

function highlightedCode() {
    return hljs.highlight(code(), { language: language.value }).value;
}

function copyToClipboard() {
    navigator.clipboard.writeText(code());
    message.info("Copied to clipboard. Happy pasting!");
}
</script>

<template>
    <div class="code-output">
        <n-flex>
            <div>
                <span>Language</span>
            </div>
            <div>
                <n-select v-model:value="language" :options="languages" size="small" style="min-width: 5rem" />
            </div>
            <div>
                <n-button @click="copyToClipboard" size="small">
                    <Icon size="16" style="margin-right: 0.3rem;">
                        <Copy16Regular />
                    </Icon>
                    Copy to clipboard
                </n-button>
            </div>
        </n-flex>

        <div class="code">
            <pre v-html="highlightedCode()" />
        </div>
    </div>
</template>

<style scoped>
.code-output {
    margin-top: 1rem;
}

.code {
    font-family: 'Courier New', Courier, monospace !important;
    font-size: 0.8rem;
    line-height: 1.5;
    display: inline-block;
    white-space: pre-wrap;
    scroll-behavior: smooth;
    overflow-x: auto;
}
</style>
